---
title: "Plots"
author: "Anna Lisa and Wenjia"
date: "2024-01-22"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=TRUE, warning=FALSE,error=FALSE}
library( "DESeq2" )
library(ggplot2)
library(tidyr)
library(tidyverse)
library(ggpubr)
library("org.Sc.sgd.db")

heatshock <- read.delim("complex_yeast_heatshock.tsv")
df_ATAC <- read.delim("ATACcounts_promotor_us500_ds100.tsv")
TFLink <- read.delim('TFLink_Saccharomyces_cerevisiae_interactions_SS_simpleFormat_v1.0.tsv')


# prepare data from heat shock
names <- grep("Wildtype", names(heatshock), value = TRUE)
df_WT <- heatshock[, names]
rownames(df_WT) <- heatshock$gene_id
# df_ATAC and df_WT will be used for following process of DEseq2

# filter only genes that both in ATAC data and RNA data are
gene_ids <- intersect(rownames(df_WT), rownames(df_ATAC))
ATAC_data <- df_ATAC[, c(1:4, 9:16, 21:28)]
RNA_data <- df_WT[gene_ids,]
order <- order(colnames(RNA_data))
RNA_data <- RNA_data[,order]

## DESeq 

# condition: 1 = 25/30_10, 2 = 25/30_30, 3 = 25/42_10, 4 = 25/42_30
##Lieber mit dem mapping file -> wenn man die Daten verändert wird es nicht mehr funktionieren!
calculateDESeq <- function(ATAC_data, RNA_data, condition){
  # fold changes of ATAC_data
  compare1 <- ATAC_data[, c(1:4, condition*4+1, condition*4+2, condition*4+3, condition*4+4)]
  coldata <- data.frame(condition = factor(c('control', 'control', 'control', 'control', 'treat', 'treat', 'treat','treat'), levels = c('control', 'treat')))
  dds <- DESeqDataSetFromMatrix(countData = compare1, colData = coldata, design= ~condition)
  dds1 <- DESeq(dds, fitType = 'mean', minReplicatesForReplace = 7, parallel = FALSE)
  res <- results(dds1, contrast = c('condition', 'treat', 'control'))

  # fold changes of RNA_data
  compare2 <- RNA_data[, c(1:3, condition*3+1, condition*3+2, condition*3+3)]
  coldata2 <- data.frame(condition = factor(c('control','control','control','treat', 'treat','treat'), levels = c('control', 'treat')))
  dds2 <- DESeqDataSetFromMatrix(countData = compare2, colData = coldata2, design= ~condition)
  dds3 <- DESeq(dds2, fitType = 'mean', minReplicatesForReplace = 7, parallel = FALSE)
  res2 <- results(dds3, contrast = c('condition', 'treat', 'control'))

  # output of the DESeq data in files
  res_df <- data.frame(res, stringsAsFactors = FALSE, check.names = FALSE)
  write.table(res_df, 'ATACData.DESeq2.txt', col.names = NA, sep = '\t', quote = FALSE)
  res_df2 <- data.frame(res2, stringsAsFactors = FALSE, check.names = FALSE)
  write.table(res_df2, 'RNAData.DESeq2.txt', col.names = NA, sep = '\t', quote = FALSE)
  res_ATAC <- res_df
  res_ATAC$gene_id <- rownames(res_ATAC)
  res_RNA <- res_df2
  res_RNA$gene_id <- rownames(res_RNA)

  join_ATAC_RNA <- inner_join(res_ATAC, res_RNA, by= "gene_id")
  return(join_ATAC_RNA)
}

makeplot <- function(ATAC_data, RNA_data, condition, highlights, TF){
    join_ATAC_RNA <- calculateDESeq(ATAC_data, RNA_data, condition)
    highlights <- join_ATAC_RNA %>% filter(gene_id %in% highlights)
    title <- switch(condition, "25/30_10", "25/30_30", "25/42_10", "25/42_30")
    #title <- paste("foldchanges of the same gene ", title, sep=" ")
    g <- ggplot(join_ATAC_RNA, aes(x = log2FoldChange.x, y = log2FoldChange.y)) +
      geom_point() +
      geom_point(data = highlights, aes(color = TF)) + 
      geom_hline(yintercept=0, linetype="dashed", color = "blue") +
      geom_vline(xintercept=0, linetype="dashed", color = "blue") +
      #labs(title = title) +
      ylab("RNA") + 
      xlab("ATAC") 
    return(g)
}

# tried to show four plots of four different condition in one figure
mergedplot <- function(ATAC_data, RNA_data, highlights, TF){
  g1 <- makeplot(ATAC_data, RNA_data, 1, highlights, TF)
  g2 <- makeplot(ATAC_data, RNA_data, 2, highlights, TF)
  g3 <- makeplot(ATAC_data, RNA_data, 3, highlights, TF)
  g4 <- makeplot(ATAC_data, RNA_data, 4, highlights, TF)
  figure <- ggarrange(g1,g2,g3,g4,
                    labels = c("25-30_10", "25-30_30", "25-42_10", "25-42_30"),
                    ncol = 2, nrow = 2)
  figure
}


TFs = c("YGL073W","YMR037C", "YKL062W" ) # HSF1, MSN2 and MSN4


# find targets from TFLink Database
TFtargets_HSF1 <- TFLink %>% filter(`Name.TF` == "HSF1")
TF_HSF1<-mapIds(org.Sc.sgd.db, keys=TFtargets_HSF1$UniprotID.Target, column="ORF", keytype="UNIPROT", multiVals="first")
TFtargets_MSN2 <- TFLink %>% filter(`Name.TF` == "MSN2")
TF_MSN2<-mapIds(org.Sc.sgd.db, keys=TFtargets_MSN2$UniprotID.Target, column="ORF", keytype="UNIPROT", multiVals="first")
TFtargets_MSN4 <- TFLink %>% filter(`Name.TF` == "MSN4")
TF_MSN4<-mapIds(org.Sc.sgd.db, keys=TFtargets_MSN4$UniprotID.Target, column="ORF", keytype="UNIPROT", multiVals="first")
TF_MSN24 <- intersect(TF_MSN2, TF_MSN4)
TF_double <- intersect(TF_MSN24, TF_HSF1)


mergedplot(ATAC_data, RNA_data, TF_HSF1, "targets of HSF1")
mergedplot(ATAC_data, RNA_data, TF_MSN24, "targets of MSN24")

# finding targets from YEASTRACT (too many)

targets_HSF1 <- unlist(YEASTRACT %>% filter(`Regulator standard` == "HSF1" & Environment == "Stress") %>% dplyr::select(`Target systematic`) %>%  distinct())

targets_MSN2 <- YEASTRACT %>% filter(`Regulator standard` == "MSN2" & Environment == "Stress")
targets_MSN4 <- YEASTRACT %>% filter(`Regulator standard` == "MSN4" & Environment == "Stress")

highlights_HSF1 <- unique(targets_HSF1)
highlights_MSN2 <- unique(targets_MSN2)
highlights_MSN4 <- unique(targets_MSN4)
highlights_MSN24 <- intersect(highlights_MSN4, highlights_MSN2)
highlights_HSF1MSN24 <- intersect(highlights_HSF1, highlights_MSN24)
# maybe in context of MSN24 explanation ? 
mergedplot(ATAC_data, RNA_data, highlights_MSN24, "targets of MSN24\n-YEASTRACT")

common_targets <- intersect(highlights_HSF1, highlights_MSN24)
#mergedplot(ATAC_data, RNA_data, common_targets, "Common targets")
```

```{r echo=TRUE}
# Diese Violin Plots für ALLE Gene --> Unten nur für die Targets
# Violin plots
heatshockDESeq <- function(RNA_data, condition){
 # fold changes of RNA_data
  compare2 <- RNA_data[, c(1:3, condition*3+1, condition*3+2, condition*3+3)]
  coldata2 <- data.frame(condition = factor(c('control','control','control','treat', 'treat','treat'), levels = c('control', 'treat')))
  dds2 <- DESeqDataSetFromMatrix(countData = compare2, colData = coldata2, design= ~condition)
  dds3 <- DESeq(dds2, fitType = 'mean', minReplicatesForReplace = 7, parallel = FALSE)
  res2 <- results(dds3, contrast = c('condition', 'treat', 'control'))
  # output of the DESeq data in files
  res_df2 <- data.frame(res2, stringsAsFactors = FALSE, check.names = FALSE)
  write.table(res_df2, 'RNAData.DESeq2.txt', col.names = NA, sep = '\t', quote = FALSE)
  res_RNA <- res_df2
  res_RNA$gene_id <- rownames(res_RNA)
  return(res_RNA)
}

# condition: Wildtype, MSN24.KO, HSF1.KD
violinplot <- function(data, condition,select=NULL){
  names <- grep(condition, names(data), value = TRUE)
  df <- heatshock[, names]
  rownames(df) <- heatshock$gene_id
  RNA_data <- df
  order <- order(colnames(RNA_data))
  RNA_data <- RNA_data[,order]
  
  foldchanges1 <- heatshockDESeq(RNA_data, 1)
  foldchanges2 <- heatshockDESeq(RNA_data, 2)
  foldchanges3 <- heatshockDESeq(RNA_data, 3)
  foldchanges4 <- heatshockDESeq(RNA_data, 4)
  newdata <- data.frame(gene_ids = foldchanges1$gene_id,
                        X37_10 = foldchanges1$log2FoldChange,
                        X37_30 = foldchanges2$log2FoldChange,
                        X42_10 = foldchanges3$log2FoldChange,
                        X42_30 = foldchanges4$log2FoldChange)
  longdata <- newdata %>%
    pivot_longer(
      cols = `X37_10`:`X42_30`, 
      names_to = "condition",
      values_to = "foldchanges",
   )
  longdata$foldchanges <- as.numeric(longdata$foldchanges)
  print(longdata)
  if(!is.null(select)){
    longdata=longdata %>% filter(gene_ids %in% select)
  }
  title <- paste("foldchanges between 25° \n and condition in ", condition)
  g <- ggplot(longdata, aes(x = condition, y = foldchanges, fill = condition)) +
    labs(title = title) +
    geom_violin() +
    ylab("foldchanges")
  return(g)
}

g1 <- violinplot(heatshock,"Wildtype",TF_HSF1)
g2 <- violinplot(heatshock,"MSN24.KO",TF_HSF1)
g3 <- violinplot(heatshock,"HSF1.KD",TF_HSF1)
## Wieso nicht noch double knockout??--> done
## lieber mit facet_grid
figure <- ggarrange(g1,g2,g3,
                    ncol = 2, nrow = 2)
figure
```








```{r Run DESEQ,  include=FALSE,message=FALSE,warning=FALSE,error=FALSE}
library(tidyverse)
library(DESeq2)
#remove.packages("readr")
#install.packages("readr")

data=read.csv2("./complex_yeast_heatshock.tsv",sep="\t",check.names=FALSE)
mapping=readr::read_tsv("sample_mapping.tsv")

mapping$condition = paste0(mapping$temperature, "_", mapping$time)
condition = unique(mapping$condition)
knockouts = unique(mapping$knockout)
comparisons = knockouts#[knockouts != "Wildtype"] 
condition = condition[condition != "25_0"]

deseq_results_list=list()

for (knock in comparisons){
  ref = mapping %>% filter(knockout == knock & temperature == "25" & time == "0")
  ref_string = paste0(knock, "_", "25", "_", "0")
  mapping_knock = mapping %>% filter(knockout == knock)
  
  for (con in condition){
    mapping_comparison = mapping_knock  %>% filter(condition == con) 
    mapping_comparison = rbind(mapping_comparison, ref)
    count_data_comparison = as.data.frame(data %>% dplyr::select(mapping_comparison$sample))
    rownames(count_data_comparison)=data$gene_id
    
    dds <- DESeqDataSetFromMatrix(countData = count_data_comparison,
                                  colData = mapping_comparison,
                                  design= ~ condition)
    dds <- DESeq(dds)
    res <- results(dds)
    results_df <- as.data.frame(res)
    deseq_results_list[[paste0(knock, "_", con , "_VS_",  ref_string )]]=res
  }
}


# Summarise comparisons
# Here we make a list only containing significant results (definition may differ)
deseq_signif_list=lapply(deseq_results_list, function(x)subset(x, padj<0.05 & abs(log2FoldChange)>1))
print(deseq_results_list)

# And compare the number of up/down regulated genes of the comparisons
number_signif=data.table::rbindlist(lapply(names(deseq_signif_list),function(x)cbind(as.data.frame(table(sign(deseq_signif_list[[x]]$log2FoldChange))),name=x)))
ggplot(number_signif,aes(x=Var1,y=Freq,fill=Var1))+geom_bar(stat="identity")+facet_wrap(~name)

# And we can compare the genes in the different comparisons
genes_signif=lapply(deseq_signif_list,function(x)rownames(x))
UpSetR::upset(UpSetR::fromList(genes_signif), nsets = length(genes_signif),order.by = "freq",mb.ratio = c(0.3, 0.7),)


fcs=do.call(cbind,(lapply(deseq_results_list,function(x)as.data.frame(x)["log2FoldChange"])))
names(fcs)=names(deseq_results_list)
fcs[is.na(fcs)]=0


pvalues=do.call(cbind,(lapply(deseq_results_list,function(x)as.data.frame(x)["padj"])))
names(pvalues)=names(deseq_results_list)
fcs[pvalues>0.05]=0

fcs$gene_id=rownames(fcs)
```


```{r Analyse}

#Anzahl der Elemente
lists=list(TF_HSF1,TF_MSN24,TF_double)
names(lists)=c("Targets_HSF1","Targets_MSN24","Targets_HSF1+MSN24")

UpSetR::upset(UpSetR::fromList(lists), nsets = length(lists),order.by = "freq",mb.ratio = c(0.3, 0.7),)

#looping though gene set and extracting gene
for(i in 1:length(lists)){
  list_name=names(lists)[i]
  target_list=lists[[i]]

  fcs_melt=reshape2::melt( fcs,id.vars="gene_id")
  
#in gene list ? Target gene?
  fcs_melt$is_target=fcs_melt$gene_id %in% target_list
  
  fcs_melt$comparison=unlist(lapply(fcs_melt$variable,function(x)gsub( ".*_(.*_.*_VS_)(.*)_(.*_.*)","\\1\\3",x)))
  fcs_melt$knockout=factor(unlist(lapply(fcs_melt$variable,function(x)gsub( ".*_(.*_.*_VS_)(.*)_(.*_.*)","\\2",x))),levels=c("Wildtype","HSF1.KD","MSN24.KO","Double.KDKO"))
  max_fc=max(abs(fcs_melt$value))
  
  #durch [fcs_melt$is_target, ]. wird nur true angezeigt, also nur für Targets und man kann Violins besser erkennen
  gg=ggplot(fcs_melt[fcs_melt$is_target, ],aes(x=comparison,y=value,fill=knockout))+
    geom_violin(position=position_dodge(width = 0.5))+
    scale_x_discrete(guide = guide_axis(angle = 90)) +theme(axis.text=element_text(size=4))+
    #scale_y_continuous(limits = c(-max_fc,max_fc))+
    facet_wrap(is_target~.,ncol=1)+
    geom_hline(yintercept =0,linewidth=.2)+
    ggtitle(list_name)
  print(gg)
}


```

```{r echo=TRUE}
#Dasselbe wie oben, aber als Boxplot --> Übersichtlicher?
# Looping durch die Zielgenlisten und Erstellung von Boxplots
for (i in 1:length(lists)) {
  list_name <- names(lists)[i]
  target_list <- lists[[i]]

  fcs_melt <- reshape2::melt(fcs, id.vars = "gene_id")

  # In der Genliste? Zielgene?
  fcs_melt$is_target <- fcs_melt$gene_id %in% target_list

  fcs_melt$comparison <- unlist(lapply(fcs_melt$variable, function(x) gsub(".*_(.*_.*_VS_)(.*)_(.*_.*)", "\\1\\3", x)))
  fcs_melt$knockout <- factor(unlist(lapply(fcs_melt$variable, function(x) gsub(".*_(.*_.*_VS_)(.*)_(.*_.*)", "\\2", x))), levels = c("Wildtype", "HSF1.KD", "MSN24.KO", "Double.KDKO"))
  max_fc <- max(abs(fcs_melt$value))

  # Durch [fcs_melt$is_target, ]. wird nur true angezeigt, also nur für Targets
  gg <- ggplot(fcs_melt[fcs_melt$is_target, ], aes(x = comparison, y = value, fill = knockout)) +
    geom_boxplot() +
    scale_x_discrete(guide = guide_axis(angle = 90)) +
    theme(axis.text = element_text(size = 4)) +
    ggtitle(paste("Boxplot der Foldchanges für ", list_name))

  print(gg)
}

```










